"""
Database Types

This file is auto-generated by Supabase CLI.

To regenerate types:
```bash
supabase gen types python --local > modules/supabase-core-python/types/database_types.py
```

Or for remote project:
```bash
supabase gen types python --project-id <project-ref> > modules/supabase-core-python/types/database_types.py
```

Example structure:
```python
from typing import TypedDict, Optional
from datetime import datetime

class Database(TypedDict):
    public: dict

# Example table type:
class ProfilesRow(TypedDict):
    id: str
    email: str
    full_name: Optional[str]
    created_at: datetime
    updated_at: datetime
```
"""

from typing import TypedDict, Any

# Placeholder type definition.
# Replace this with actual generated types from Supabase CLI.
class Database(TypedDict):
    """Placeholder database type. Replace with generated types."""
    public: dict[str, Any]

