/**
 * Database Types
 * 
 * This file is auto-generated by Supabase CLI.
 * 
 * To regenerate types:
 * ```bash
 * supabase gen types typescript --local > modules/supabase-core-typescript/types/database-types.ts
 * ```
 * 
 * Or for remote project:
 * ```bash
 * supabase gen types typescript --project-id <project-ref> > modules/supabase-core-typescript/types/database-types.ts
 * ```
 * 
 * @see modules/supabase-core-typescript/src/types/generate-types.ts for instructions
 */

/**
 * Placeholder type definition.
 * Replace this with actual generated types from Supabase CLI.
 * 
 * Example structure:
 * ```typescript
 * export type Json =
 *   | string
 *   | number
 *   | boolean
 *   | null
 *   | { [key: string]: Json | undefined }
 *   | Json[]
 * 
 * export interface Database {
 *   public: {
 *     Tables: {
 *       profiles: {
 *         Row: {
 *           id: string
 *           email: string
 *           full_name: string | null
 *           created_at: string
 *           updated_at: string
 *         }
 *         Insert: { ... }
 *         Update: { ... }
 *       }
 *     }
 *     Views: { ... }
 *     Functions: { ... }
 *   }
 * }
 * ```
 */
export type Database = {
  public: {
    Tables: Record<string, any>
    Views: Record<string, any>
    Functions: Record<string, any>
  }
}

